name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Install dependencies and run tests for user service
      - name: Install dependencies and run tests for user service
        working-directory: ./cicd-project/users
        run: |
          npm install
          npm test

      # Install dependencies and run tests for product service
      - name: Install dependencies and run tests for product service
        working-directory: ./cicd-project/product
        run: |
          npm install
          npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Deployment steps for each service can be added here
      # Example:
      # - name: Deploy user service
      #   working-directory: ./cicd-project/user
      #   run: |
      #     npm run deploy

      # - name: Deploy product service
      #   working-directory: ./cicd-project/product
      #   run: |
      #     npm run deploy
