name: Run JavaScript Code

on:
  push:
    branches:
      - main

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for user service
        working-directory: ./users  # Navigate to users directory (adjust for product)
        run: npm install || exit 1  # Add error handling (optional)

      - name: Run user service (Example)
        working-directory: ./users/src  # Navigate to users/src directory (adjust if needed)
        run: node index.js  # Replace with your actual entry point script

      - name: Install dependencies (Repeat for product service if needed)
        working-directory: ./product  # Optional, repeat for product service
        run: npm install || exit 1  # Add error handling (optional)

      - name: Run product service (Example)
        working-directory: ./product/src  # Optional, repeat for product service
        run: node index.js  # Replace with your actual entry point script
