name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for user service
        working-directory: ./cicd-project/users
        run: npm install

      - name: Install dependencies for product service
        working-directory: ./cicd-project/product
        run: npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy user service
        working-directory: ./cicd-project/users
        run: npm run deploy

      - name: Deploy product service
        working-directory: ./cicd-project/product
        run: npm run deploy
